# Generated by Django 5.2.13 on 2026-04-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default='2000-01-01')),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(default='Karnataka', max_length=50)),
                ('city', models.CharField(default='Unknown', max_length=50)),
                ('pincode', models.CharField(default='000000', max_length=10)),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_widow', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
