# Generated by Django 5.2.13 on 2026-04-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=20, unique=True)),
                ('pension_type', models.CharField(choices=[('Old Age', 'Old Age'), ('Disability', 'Disability'), ('Widow', 'Widow')], default='Old Age', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('citizen_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.citizencard')),
            ],
        ),
    ]
